# Docker Compose for Development
# Hot reload enabled, logs visible, volumes mounted

services:
  # Backend Service - Development Mode
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: udemy-predictor-backend-dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/udemy_predictions.db
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      - backend-data:/app/data
      # Don't mount pycache
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend Service - Development Mode with Vite Dev Server
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    container_name: udemy-predictor-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
    driver: local

