services:
  # Backend Service - Production
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: udemy-predictor-backend-prod
    environment:
      - DATABASE_URL=sqlite:///./data/udemy_predictions.db
      - CORS_ORIGINS=${CORS_ORIGINS}
    volumes:
      - backend-data:/app/data
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Không expose port ra ngoài, chỉ dùng trong network

  # Frontend Service - Production
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: udemy-predictor-frontend-prod
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    # Không expose port, sẽ dùng reverse proxy

  # Reverse Proxy - Nginx
  nginx:
    image: nginx:alpine
    container_name: udemy-predictor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
    driver: local


